### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by cagcak** [sindresorhus/os-locale#26]
`TypeError: osLocale.then is not a function`

log:

```
λ node render.js

  var region = osLocale(locale);
                        ^

ReferenceError: locale is not defined
    at Object.<anonymous> (render.js:6:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

```

**Comment by sindresorhus** [comment]
You're using it incorrectly or using an older version.

**Comment by PriyBan** [comment]
I'm still seeing this issue, i tried on v2.0.0. Please let me know at which version this got fixed.
